module.exports = [
  {
    grade: 'K1',
    firstName: 'Student',
    lastName: 'EN',
    email: 'student@york-e.com',
    schoolId: 'schYpEN01',
    avatar: 'books',
  },
  {
    grade: 'K1',
    firstName: 'Student',
    lastName: 'Two',
    email: 'student-two@york-e.com',
    schoolId: 'schYpEN01',
    avatar: 'ladybird',
  },
  {
    grade: 'K1',
    firstName: 'Student',
    lastName: 'Three',
    email: 'student-three@york-e.com',
    schoolId: 'schYpEN01',
    avatar: 'paint',
  },
  {
    grade: 'K1',
    firstName: 'Student',
    lastName: 'Four',
    email: 'student-four@york-e.com',
    schoolId: 'schYpEN01',
    avatar: 'tableTennis',
  },
  {
    grade: 'K1',
    firstName: 'Student',
    lastName: 'Five',
    email: 'student-five@york-e.com',
    schoolId: 'schYpEN01',
    avatar: 'tomato',
  },
  {
    grade: 'K1',
    firstName: 'Student',
    lastName: 'Invited',
    email: 'student-invited@york-e.com',
    schoolId: 'schYpEN01',
    avatar: 'chocolate',
  },
];
